################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Get in touch if you need help with; Software, iPads, Internet TV, Skype, Remote assistance. We can fix your computer too!"
# copyright
copyright = "Designed By [Tropicaldo](https://tropicaldo.com/) & Developed By [Marco](https://tropicaldo.com/)"



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
home = "Accueil"
# footer content
footer_content = "Contactez-nous si vous avez besoin d'aide ; Logiciels, iPads, Internet TV, Skype, Assistance à distance. Nous pouvons également réparer votre ordinateur !"
# copyright
copyright = "Designed By [Tropicaldo](https://tropicaldo.com/) & Developed By [Marco](https://tropicaldo.com/)"


################################### Spanish language #####################################
[Es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Volver"
# footer content
footer_content = "Póngase en contacto si necesita ayuda con; Software, iPads, Internet TV, Skype, Asistencia remota. ¡También podemos reparar tu computadora!"
# copyright
copyright = "Designed By [Tropicaldo](https://tropicaldo.com/) & Developed By [Marco](https://tropicaldo.com/)"